### ISSUE TITLE
Can't search licenses by domain?

### ISSUE THREAD

**Issue by MangoMarcus** [craftcms/console#113]
### Description

I'm trying to search craft and plugin licenses using a domain but it returns no results. I've also tried to search with the full licence key which doesn't seem to be supported, although the first 4 chars does work. It also generally seems quite sluggish and slow.

### Steps to reproduce

1. Go to Licences > Plugins
2. Before searching for anything wait for the licences to load, then copy the domain for any of the results
3. Search by that domain - yields "No results"

Thanks!

**Comment by timkelty** [comment]
Thanks for reporting, @MangoMarcus. We're taking a look.

**Comment by timkelty** [comment]
@MangoMarcus should be resolved – For Plugin licenses, you can now search on the CMS License Key and the domain.

I made a separate issue for the sluggishness: https://github.com/craftcms/console/issues/113

**Comment by MangoMarcus** [comment]
@timkelty awesome, thanks for the quick turn around!

Think you meant #114 for the sluggishness? Thanks

**Comment by timkelty** [comment]
Indeed! Thanks!
