### ISSUE TITLE
Sorting the Orders table by the date column fails in some cases

### ISSUE THREAD

**Issue by rungta** [craftcms/console#116]
### Description

The Orders table does not appear to be sorted by the date by default. I would expect the latest order to be shown as the first item here. Nevertheless, clicking on the _Date_ column header sorts the table in ascending order (as expected), but has no change when clicked on a second time and the sort direction should have changed.

Ascending order works:
<img width="650" alt="image" src="https://github.com/user-attachments/assets/7de5705f-e525-4471-8792-b6d18ec723b6">

Descending order fails:
<img width="665" alt="image" src="https://github.com/user-attachments/assets/b65de5c8-44b6-497f-90dc-8ee4a01f1561">

**Comment by rungta** [comment]
@brianjhanson Thanks, works fine now! Is it possible to also sort this _Orders > Completed_ list reverse chronologically by default? Strange to not see the latest order as the first item.

**Comment by brianjhanson** [comment]
@rungta good call! Just pushed an update that will sort all organization orders by date descending.
