### ISSUE TITLE
Discount is not being applied

### ISSUE THREAD

**Issue by HannahDeWachter** [craftcms/console#117]
### Description
I tried to add a Coupon code in checkout, after clicking on Apply I get the message "Coupon code applied." however in the Summary of my order, there is no discount added.
The coupon code should be valid for 20 Craft licences and according to our records we should still have a few available.

### Steps to reproduce

1. Having following items in my cart: 1 new Craft Pro licence, several different new plugin licences
2. Fill in a Coupon code and click on "Apply"

**Comment by timkelty** [comment]
@HannahDeWachter this should be resolved. Can you try again?

**Comment by HannahDeWachter** [comment]
Hi @timkelty,
It works again! Thank you!
