### ISSUE TITLE
[FR] Provide unsubscribe option for "Important license info" emails

### ISSUE THREAD

**Issue by ryanmasuga** [craftcms/console#26]
I want to unsubscribe from "Important license info" emails. Buying a commercial plugin shouldn't subject one to a lifetime of email remainders, or put the burden on the user to make an email filter to keep these out of an inbox. I imagine these could become a nuisance after a few years of buying commercial plugins.

I think unsubscribing from these is a legitimate request because the email isn't critical, as we can get this same info in other places (logging into Craft ID site, viewing CP of a site where an outdated plugin is installed).

**Comment by timkelty** [comment]
@ryanmasuga In Console, user settings now have a Notifications page with an option to unsubscribe from all non-essential emails.

![CleanShot 2024-04-09 at 10 58 12@2x](https://github.com/craftcms/console/assets/18329/34234f54-b40c-4d40-8d53-cf6070b91e38)
