### ISSUE TITLE
Out-of-control icon in Plugin Store

### ISSUE THREAD

**Issue by bencroker** [craftcms/console#84]
### Description

The warning icon for abandoned plugins is getting a fixed width of 448px, instead of allowing it to fill its container element, in the plugin store.

### Steps to reproduce

1. Visit any abandoned plugin, for example: https://plugins.craftcms.com/one-plugin-fields?craft4=

![CleanShot 2024-02-25 at 07 43 51@2x](https://github.com/craftcms/console/assets/57572400/43f27c6c-e885-43d4-a1ea-8b9e17e954f7)

**Comment by benjamindavid** [comment]
Should be fixed now, thanks for the feedback @bencroker!
