### ISSUE TITLE
Updating cart gives error

### ISSUE THREAD

**Issue by HannahDeWachter** [craftcms/console#87]
### Description
When trying to update my cart (disable auto-renew or remove an item) it gives an error. I went to look in the Network tab of my browser and saw following validation error: _Invalid upgrade edition: standard_

Is it possible to empty out the whole cart?

### Steps to reproduce

1. Go to my (filled) cart
2. Click on Remove

**Comment by angrybrad** [comment]
@HannahDeWachter can you email support@craftcms.com with the Craft Console / Organization account you're seeing this in?

**Comment by timkelty** [comment]
>Is it possible to empty out the whole cart?

@HannahDeWachter – It wasn't, which was a bit silly. You'll now find a "Clear Cart" button in the top right.

Should solve you immediate problem. We're still investigating the underlying issue. Thanks!
